baseURL = "http://teskemj.github.io"
languageCode = "en-us"
title = "Teske's Blog"
theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"